### ISSUE TITLE
QWERTZ Support

### ISSUE THREAD

**Issue by TimoLins** [mmckegg/loop-drop-app#104]
It would be cool to support QWERTZ-Keyboards without messing with the sourcecode...

**Comment by mmckegg** [comment]
Yes good point. 

Will try and auto detect but if that's too hard, will probably add a second drop down on qwerty keys that let's you choose layout.

**Comment by mmckegg** [comment]
Great, can detect layout on Mac & Windows using https://github.com/atom/keyboard-layout

**Comment by mmckegg** [comment]
@TimoLins: Please try out the latest version from GitHub! Only supports Mac German right now, but easy to [send a pull request](https://github.com/loopjs/loop-qwerty) :)
