### ISSUE TITLE
keyboard-layout not working on Linux

### ISSUE THREAD

**Issue by ahdinosaur** [mmckegg/loop-drop-app#105]
using 043f8e53e6c518f0b88e5275c3c3045a2587ad24 on Debian Linux, if i run the `keyboard-layout` script:

```
$ node scripts/keyboard-layout.js 
undefined
```

**Comment by mmckegg** [comment]
There's no point in getting this working on linux because can't get accurate key events anyway.

> `keyIdentifier` on linux is just `keyCode.toString(16)`

**Comment by mmckegg** [comment]
Everything will be okay once this lands:

https://code.google.com/p/chromium/issues/detail?id=227231

**Comment by mmckegg** [comment]
removed keyboard-layout, now using custom command line hackery for each OS: 
[lib/watch-keyboard-layout.js](https://github.com/mmckegg/loop-drop-app/blob/master/lib/watch-keyboard-layout.js)
