### ISSUE TITLE
some qwerty keys not working on Linux

### ISSUE THREAD

**Issue by ahdinosaur** [mmckegg/loop-drop-app#106]
using the latest git master on Debian Linux, some qwerty controller keys don't work, like undo, redo, halve, double, and other side keys not working but the inner grid keys are working.

this might be related to https://github.com/mmckegg/loop-drop-app/issues/105, although on [slack](https://loopdrop.slack.com/) @mmckegg says:

> As for your other issues @ahdinosaur, maybe caused by me switching to use event.keyIdentifier for non English keyboard support. Maybe it's different on Linux.

[v2.9.0](https://github.com/mmckegg/loop-drop-app/releases/tag/v2.9.0) works great. :smile:

**Comment by ahdinosaur** [comment]
seems my `event.keyIdentifier`s don't match the actual characters i press.

tested this with:

```js
window.addEventListener('keydown', function (ev) {
  console.log(String.fromCharCode(parseInt(ev.keyIdentifier.slice(2), 16)))
})
```

**Comment by mmckegg** [comment]
seems to be exactly the same problem under Ubuntu.

Not sure if I'm relieved or annoyed.

**Comment by mmckegg** [comment]
Found these running Ubuntu on a MacBook with qwerty keys

```
U+00C0    `
U+0009    Tab
U+00A0   Shift
U+00A1   Shift
U+00A2   Control
U+00A4   Alt
U+00E1   Alt
Win          Meta
U+00BD   -
U+00BB   =
U+0008    Backspace
U+00DB   [
U+00DD   ]
U+00DC   \
U+00BA   ;
U+00DE   '
U+00BC   ,
U+00BE   .
U+00BF    /
```

**Comment by mmckegg** [comment]
Probably fixed by https://github.com/loopjs/loop-qwerty/commit/4adcea9

**Comment by ahdinosaur** [comment]
awesome! latest git master works for me now.

**Comment by mmckegg** [comment]
de mappings:

```
U+00E5    ^
U+00DB   ß --- conflicts with [
U+00E5    ´
U+00BA   ü ---- conflicts with ;
U+00BB   + ---- conflicts with =
U+00BF   # ---- conflicts with /
U+00C0   ö
U+00DE   ä --- conflicts with '
```

There's a lot of conflicts there :disappointed:

**Comment by mmckegg** [comment]
So it turns out `keyIdentifier` on linux is just keyCode.toString(16) :disappointed: HOW STUPID IS THAT!? :anger:
