### ISSUE TITLE
node_modules/lib symlink sometimes not created on windows

### ISSUE THREAD

**Issue by sabakilai** [mmckegg/loop-drop-app#175]
Im getting this error "the app provided is not a valid electron app. Cant find module lib/menu"

**Comment by mmckegg** [comment]
Yeah, I've had a couple of reports of this happening. I haven't yet been able to reproduce.

Try deleting the node_modules folder inside loop-drop-app/ and then re-running `npm install`.

1. What OS and version are you running?
2. What version of Node.js and npm are you using?

**Comment by sabakilai** [comment]
1. win 8.1
2 node - 5.5.0 npm - 3.3.12

deleting the node modules doesnt help

**Comment by mmckegg** [comment]
Not sure why this is occurring, but it seems like the symlink `loop-drop-app/node_modules/lib -> loop-drop-app/lib` isn't working.

You can try manually copying the `lib` folder into `node_modules` and see if that makes it work.

**Comment by sabakilai** [comment]
Ah yeah!! It works now!!
