### ISSUE TITLE
2.17.1 32-bit MSI correct?

### ISSUE THREAD

**Issue by azwirko** [mmckegg/loop-drop-app#204]
I note the 32-bit MSI file here

https://github.com/mmckegg/loop-drop-app/releases/download/v2.17.1/Loop.Drop.v2.17.1.msi 

is only 7 KB - no where near the 40-50 MB the other MSI files have been.  Downloading and running this current MSI results in an installer error.

**Comment by mmckegg** [comment]
The latest release v3.0.1 now has a working windows build.

https://github.com/mmckegg/loop-drop-app/releases
