### ISSUE TITLE
Where is the best discussion, hangout for Web MIDI devs?

### ISSUE THREAD

**Issue by davidhtims** [mmckegg/loop-drop-app#206]
@mmckegg 
Hi Matt, I have some questions on starting out on an Electron MIDI/Audio project, do you frequent any place? Google doesn't help much so I'm guessing slack is the place?
Dave

**Comment by mmckegg** [comment]
Yeah! There's a really great Web Audio slack. You can join here: https://web-audio-slackin.herokuapp.com

**Comment by davidhtims** [comment]
Thanks Matt, I'm joined up ..
