### ISSUE TITLE
seems to start lagging after being used for a while

### ISSUE THREAD

**Issue by mmckegg** [mmckegg/loop-drop-app#32]
also on stable chrome, sometimes will just crash when it all gets too much, although in canary it doesn't crash, but the lag seems to be worse.

**Comment by mmckegg** [comment]
hopefully this is a lot better in v2

reduced CPU usage of oscillators and envelopes. 

lagging is caused by audio thread CPU usage exceeding 100%.

**Comment by feross** [comment]
Yep, I just ran into this. Over time, the chance of getting a drop out seems to go up. After a while, it's basically impossible to continue without a restart, and the music sometimes even completely stops. CPU at 100%.

Btw Matt: I got a Launchpad Mini and this is so much fun!! Amazing project.

**Comment by feross** [comment]
Even if you reset all active loops and start over just adding a few beats, it seems to overwhelm the CPU like there's a bunch of extra work being done that wasn't happening when I first started.

**Comment by mmckegg** [comment]
Yeah, it almost seems like something isn't being cleaned up properly. I think it's in the audio thread though.

**Comment by feross** [comment]
Anecdotally, the lag starts to happen after I've been using button 5 (Beat Hold).

**Comment by feross** [comment]
The only solution seems to be to restart Loop Drop when this happens.

**Comment by feross** [comment]
Actually, closing the setup seems to do the trick, too.

**Comment by mmckegg** [comment]
I found that Chrome 43 (and 44) seemed to be particularly bad. Could only hold down about half as many triggers before hitting the limit.

But Chrome 45 (current canary) seems to be working even better than 42, and doesn't seem to have the same problem with garbage collection dropouts. So this is great :smile: 

I'm really hoping that a lot of the performance problems will just fix themselves over time :pray:

**Comment by ahdinosaur** [comment]
@mmckegg you might be interested in this thread on how to control the v8 garbage collector with cli params: https://github.com/nodejs/node/issues/3370, although you might already be aware of these things.

> For a kitchen sink example with arbitrary values:
>
```
node --gc_global --optimize_for_size --max_old_space_size=960 --use_idle_notification --always_compact --max_executable_size=64 --gc_interval=100 --expose_gc server.js
```

**Comment by mmckegg** [comment]
okay so Chrome 47 has done some magic, and this doesn't seem to be a problem anymore! Hurray! 

:tada: :balloon: :rainbow: :star2: 

There are still a few glitches, but they are no longer seem to be getting worse over time, instead they're just garbage collection related most likely.
