### ISSUE TITLE
missing module deps

### ISSUE THREAD

**Issue by ahdinosaur** [mmckegg/loop-drop-app#47]
> $ npm run build                              

> loop-drop@1.11.3 build /home/michael/repos/mmckegg/loop-drop-app
> node build -d
>
>** REBUILD ERROR **
module "observ" not found from "./context/index.js"
** REBUILD ERROR **
module "observ/watch" not found from "./context/index.js"
** REBUILD ERROR **
module "bopper" not found from "./context/index.js"
** REBUILD ERROR **
module "observ/watch" not found from "./views/audio-meter.js"
** REBUILD ERROR **
module "observ" not found from "./editor/index.js"
** REBUILD ERROR **
module "observ/watch" not found from "./editor/index.js"
** REBUILD ERROR **
module "observ" not found from "./loop-launchpad/index.js"
** REBUILD ERROR **
module "observ/watch" not found from "./loop-launchpad/index.js"
** REBUILD ERROR **
module "observ/watch" not found from "./loop-drop-editor/raw.js"
** REBUILD ERROR **
module "observ-grid" not found from "./loop-qwerty/index.js"
** REBUILD ERROR **
module "observ-grid/grabber" not found from "./loop-qwerty/index.js"
** REBUILD ERROR **
module "observ-grid/indexes-where-contains" not found from "./loop-qwerty/index.js"
** REBUILD ERROR **
module "observ/watch" not found from "./lib/map-watch-diff-stack.js"
** REBUILD ERROR **
module "observ/watch" not found from "./controller/grid-state-hook.js"
** REBUILD ERROR **
module "observ/watch" not found from "./params/wave-hook.js"

- [x] `loop-drop-app` needs `observ` and `bopper`
- [x] `loop-qwerty` needs `observ-grid`
- [x] `loop-drop-editor` needs `observ`
- [x] `loop-launchpad` needs `observ`

**Comment by mmckegg** [comment]
all fixed!
