### ISSUE TITLE
design and marketing

### ISSUE THREAD

**Issue by ahdinosaur** [mmckegg/loop-drop-app#68]
right now Loop Drop is technically available, but it's not accessible. i want to work towards a proper website, complete with design and marketing. :rocket: 

i recruited [Finlay](http://finlaysh.com/) to help us a bit, here's what he came up with:

- full [repo](https://github.com/ahdinosaur/loop-drop-design)
- mood board [pdf](https://github.com/ahdinosaur/loop-drop-design/blob/master/Mood%20Board.pdf)
- design [images](https://imgur.com/a/HrqEW/all)
- competitor analysis [pdf](https://github.com/ahdinosaur/loop-drop-design/blob/master/Competitor%20Analysis/AbletonLive.pdf) and [images](https://imgur.com/a/rIbmc)

licensed under [Creative Commons Attribution-ShareAlike](https://creativecommons.org/licenses/by-sa/4.0/).

i want to open up the design process to as many perspectives as possible:

- what is Loop Drop?
- how does Loop Drop make us feel?
- who is our target audience?
- how do we want to communicate Loop Drop?
- ...?

**Comment by mmckegg** [comment]
yeah a proper loop drop website is a conversation that needs starting! Thanks for this!

I'll write up some proper thoughts later, unfortunately I can't remember what I said last night in person (scrumpy thoughts...).

![image](https://cloud.githubusercontent.com/assets/66834/7310328/392630f8-ea7e-11e4-9710-7a82f78a2570.png)

**Comment by ahdinosaur** [comment]
i remember you wanting to communicate the concepts of grids and loops.

i reckon for the MVP website we need:
- [ ] a swaggin' banner image showing off a Loop Drop setup
- [ ] a tagline
- [ ] a logo
- [ ] a video demoing and describing the app
- [ ] a couple images with sentences showing off specific features of the app
- [ ] a large, easy-to-find DOWNLOAD button that starts a payment -> download -> install flow (installed app should include awesome samples)
- [ ] basic help documentation, possibly mirrored in-app

for more awesomeness:
- instead of showing images of app features, embed pieces of the app in the website (!)
- a discourse forum setup on a subdomain (i can do this)
- maybe some sort of pay-what-you-want flow that incentivizes people to pay more ("if you pay more than the average, we'll give you a :chocolate_bar:")
- ...?

**Comment by mmckegg** [comment]
:+1: that's all sounding pretty good :smile: 

I think I was saying the the logo should communicate the idea of loop drop to users, somehow symbolise grids and loops. Doesn't matter if it's not obvious until someone has used the app though (as long as it's a nice design).

It would be nice if the **loops and grids** theme was continued throughout the entire website design. Also there needs to be a clear emphasis on **improvisation**.

I really like the idea of pulling out pieces of loop drop functionality and putting them on the website as **interactive feature demos**. But obviously this won't be straight forward.

Should we stick with loopjs.com for now, or come up with something more loop drop specific?

**Comment by mmckegg** [comment]
I'm going to close this issue since most of what was discussed above has been completed!

@ahdinosaur: We should open a new issue for documentation.
