### ISSUE TITLE
RELEASE LOOP DROP!

### ISSUE THREAD

**Issue by mmckegg** [mmckegg/loop-drop-app#81]
- [x] **Package up into electron app**
  - [x] get loading with electron
  - [x] figure out how to convert Buffers -> ArrayBuffers
  - [x] new welcome screen
    - [x] auto install demo content
    - [x] create new project
    - [x] open existing project
    - [x] show new version available
  - [x] record output from sidebar
  - [x] improve sample drag and drop, allow drop in more places (slot, slot list)
  - [x] mac bundler
  - [x] include compressed Quantum Loop in demo project
  - [x] compress setup script - trims samples to in and out points and converts to ogg. Removes unused files

- [x] **Create simple website** (probably at loopjs.com)
  - [x] loop drop in action video
  - [x] quick start guide with images
    - [x] start with qwerty demo setup
    - [x] how to use with launchpad
    - [x] using audio samples
  - [x] buy button ($40 USD?)
    - [x] purchase via paypal
    - [x] instant download
    - [x] send email with redownload link and refund option
    - [x] create page to handle refunds that tracks reason
  - [x] update instruction page
    - [x] instructions: use link in email, or enter your email address to resend
    - [x] email resend form

- [ ] **deploy!**
  - [ ] some sort of automated build system for new versions

**Comment by mmckegg** [comment]
and I'm going to do all of this tonight :wrench:  :package: :ship: :boom: :expressionless: 

:laughing:

**Comment by ahdinosaur** [comment]
!!! :boom: :tada: :fire: !!!

**Comment by mmckegg** [comment]
wow such progress!

**Comment by NHQ** [comment]
If you're using browserify, which uses feross's buffer rewrite, then no conversion is necessary from buffer to arraybuffer, cuz buffers are gussied up UInt8Arrays:

```js
var buf = new Buffer(1024)
var arrayBuffer = buf.buffer
```

**Comment by mmckegg** [comment]
@NHQ was using browserify before, now using electron. 

https://github.com/substack/buffer-to-uint8array did the trick, that way it works in both!

**Comment by mmckegg** [comment]
WOOHOO! It's ALIVE!! 

http://loopjs.com/

**Comment by ahdinosaur** [comment]
yeaaaaaaaaaaaaahhhhhhhhhh!!! :dancer: :dancers:
